name: Create releases
on:
  push:
    branches:
      - main

jobs:
  release:
    name: release
    if: github.ref == 'refs/heads/main' && github.repository == 'CyclingBits/claude-code-sdk-java'
    runs-on: ubuntu-latest
    environment: production-release

    steps:
      - uses: actions/checkout@v4

      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: java
          package-name: claude-code-sdk-java

      - name: Set up Java
        if: ${{ steps.release.outputs.releases_created }}
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: |
            8
            17
          cache: gradle

      - name: Set up Gradle
        if: ${{ steps.release.outputs.releases_created }}
        uses: gradle/gradle-build-action@v2

      - name: Publish to Sonatype
        if: ${{ steps.release.outputs.releases_created }}
        run: |-
          printenv -- GPG_SIGNING_KEY | gpg --batch --passphrase-fd 3 --import 3<<< "$GPG_SIGNING_PASSWORD"
          export GPG_SIGNING_KEY_ID="$(gpg --with-colons --list-keys | awk -F : -- '/^pub:/ { getline; print "0x" substr($10, length($10) - 7) }')"
          ./gradlew publishAndReleaseToMavenCentral --stacktrace -PmavenCentralUsername="$SONATYPE_USERNAME" -PmavenCentralPassword="$SONATYPE_PASSWORD" -PsigningInMemoryKeyId="$GPG_SIGNING_KEY_ID" -PsigningInMemoryKey="$GPG_SIGNING_KEY" -PsigningInMemoryKeyPassword="$GPG_SIGNING_PASSWORD" --no-configuration-cache
        env:
          SONATYPE_USERNAME: ${{ secrets.CYCLINGBITS_SONATYPE_USERNAME || secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.CYCLINGBITS_SONATYPE_PASSWORD || secrets.SONATYPE_PASSWORD }}
          GPG_SIGNING_KEY: ${{ secrets.CYCLINGBITS_SONATYPE_GPG_SIGNING_KEY || secrets.GPG_SIGNING_KEY }}
          GPG_SIGNING_PASSWORD: ${{ secrets.CYCLINGBITS_SONATYPE_GPG_SIGNING_PASSWORD || secrets.GPG_SIGNING_PASSWORD }}
